### ISSUE TITLE
デザイン

### ISSUE THREAD

**Issue by ykmtsd** [KU-eSports/KUeST-PR#11]

**Comment by ykmtsd** [comment]
メインの内容がスプラカスタムの告知になりそうなので、デザインはスプラトゥーンのオマージュ風にしたいと思います。

**Comment by ykmtsd** [comment]
https://github.com/KU-eSports/kuest-streaming/issues/43#issuecomment-1275533088

この飛沫のイラストをポスターに使いたいです。 使ってもよろしいでしょうか？@Tooooomo

**Comment by Tooooomo** [comment]
しぶきを使うのは大丈夫だけどこのイラストはラフで適当に作ったやつだから本番はちゃんと作り直した方がいいかも
それとデザインをあまりスプラトゥーンに寄せちゃうとうちがスプラトゥーンのサークルだと思われるかもしれない
とりあえず役割分担してラフかいてみましょう

**Comment by ykmtsd** [comment]
わかりました
役割分担しましょう

1人が背景を考える
もう1人が文章と構図を考える
といった感じですか？

**Comment by Tooooomo** [comment]
ラフは一人が描かないと統一感が無くなっちゃうからまずはラフ係とそれ以外の雑務係かな
できればイラレ持ってるしなかさんお願いしたい
