### ISSUE TITLE
人数集めの方法

### ISSUE THREAD

**Issue by Tooooomo** [KU-eSports/KUeST-PR#13]
### Discussed in https://github.com/KU-eSports/KUeST-PR/discussions/12

<div type='discussions-op-text'>

<sup>Originally posted by **Tooooomo** October 18, 2022</sup>
# ポスターに代わる宣伝方法
ポスターによる宣伝ができなくなった以上、代替策を考える必要があります。

## *現在の参加者(10/21現在)
参加確定：2  
参加可能性あり：6

### 現在実行している手段
- KUeSTアカウントでつぶやく

### 考えられる手段
- Splatoon3ロールがついている人にメンション、DM
- Splatoon3を所持している知り合いに直接お願い

### 開催可否を決めるデッドライン
11/5(土)  
部会時点の人数で開催の可否を決定

***

アスタリスクのついた欄については加筆を、その他追記あればお願いします
</div>

**Comment by ykmtsd** [comment]
## 現在の参加者
運営抜きの人数です
にゃあさんの当日の仕事はVC誘導なのでプレイヤーにカウントしました

参加確定 : 2 (参加のリアクションをつけてくれた人数)
参加可能性あり : 6 (スプラのロールがついている人数)

明らかに足りないです

**Comment by N4K4eight** [comment]
しめきりは1週間前の部会にしましょう。

**Comment by N4K4eight** [comment]
人集めの方法として、
別のSNSをやるっていうのはどうでしょうか。
ビラ配りが許されるならビラを配りたいです。

**Comment by Tooooomo** [comment]
### ビラ配りについて
#### 準備に必要なこと
- 学務に非公認団体がビラの配布をしていいかの確認  
- ビラの下書き (イラレ使用するならなかさん @N4K4eight がいいかと)  
もしビラ配布が認められなかった場合にTwitterなどの告知に再利用できるようなデザインにするのをおすすめします
- ビラ配布要員の捻出 (運営から出すか、サーバーで配る人を募集するか)
KUeST-streamingにて開発中のメンバーは拘束したくないのでできればそれ以外のメンバーで
- 配布期間の決定

### Twitter以外のSNSについて
- 使用SNSの決定
- アカウントの作成
- 管理者の決定 (取り急ぎカスタム開催までなかさんでも)
- テキスト以外(画像や動画等)の内容を宣伝に盛り込むならそれらの作成

***

とりあえずの議題はこれくらいでしょうか

**Comment by Ere4CKywyEHz** [comment]
学務にビラ配りしていいか聞きます

**Comment by N4K4eight** [comment]
## ビラの内容（優先度順）
- サークル名
- カスタム開催のお知らせ、日時
- ディスコードサーバー
- ツイッターアカウント

**Comment by Ere4CKywyEHz** [comment]
## ビラ配りの場所と日時
場所：総教前
時間：昼休み
目標：1日100枚配る

**Comment by Ere4CKywyEHz** [comment]
今日学務からメールの返信来ませんでした

**Comment by Ere4CKywyEHz** [comment]
今日も返信来なかったので、もうビラ配っていいんじゃない？
