### ISSUE TITLE
宣伝用ポスターの作成

### ISSUE THREAD

**Issue by ykmtsd** [KU-eSports/KUeST-PR#2]
総合教育棟エリアに掲示する宣伝用ポスターを作ります。
主にtomoさんにデザインの助言を頂きたいです。（他の方も是非助言お願いします）

**Comment by ykmtsd** [comment]
製作に取り掛かる前に決めることリスト

・ポスターのサイズ
・載せる内容
・大まかなデザイン
・製作期日
・予算
・印刷枚数
・印刷方法（外注 or 自作）
・使用する紙の種類

**Comment by Tooooomo** [comment]
KUeST-streamingみたいに新しくRoadmapのissue立ててそこから細分化したissueにしましょうか
向こうの書き方参考にしてもらって、markdownの書き方で調べても分からないところがあったら気軽に聞いてください
