### ISSUE TITLE
製作期日

### ISSUE THREAD

**Issue by ykmtsd** [KU-eSports/KUeST-PR#6]

**Comment by ykmtsd** [comment]
スプラカスタムが11/20なので、10月中にポスター完成させて2週間は宣伝する期間作りたいですね。

**Comment by secchanu** [comment]
11/12開催じゃなかったっけ

**Comment by ykmtsd** [comment]
> 11/12開催じゃなかったっけ

12日ですね
この前も間違えた気がするw

**Comment by N4K4eight** [comment]
審査に関してどれだけかかるかは分かりません。確認の必要があります。

**Comment by ykmtsd** [comment]
> 審査に関してどれだけかかるかは分かりません。確認の必要があります。

できるだけ早急に確認お願いします。
なかさん忙しいなら僕が学務にメール書きます。

**Comment by N4K4eight** [comment]
んじゃあお願いします
